info:
  namespace: hammeritem
categories:
  moonday:
    enabled: true
    icon: hammeritem:wuren_mooncake
    name: '中秋'
    items:
      - hammerfurniture:mooncake_model
      - hammeritem:chocolate_mooncake
      - hammeritem:chorus_mooncake
      - hammeritem:cpk_mooncake
      - hammeritem:diamond_mooncake
      - hammeritem:dousha_mooncake
      - hammeritem:emerald_mooncake
      - hammeritem:gold_mooncake
      - hammeritem:honey_mooncake
      - hammeritem:ice_mooncake
      - hammeritem:lianrong_mooncake
      - hammeritem:slime_mooncake
      - hammeritem:wuren_mooncake
      - hammeritem:mooncake
      - hammeritem:flat_mooncake
   save_the_moonday:
    enabled: true
    icon: hammeritem:yolk_mooncake
    name: '中秋-拯救大饼'
    items:
      - hammeritem:kita_mooncake
      - hammeritem:nijika_mooncake
      - hammeritem:hard_mooncake
      - hammeritem:celeste_mooncake
      - hammeritem:icy_mooncake_alt
      - hammeritem:yuzu_mooncake
      - hammeritem:silk_mooncake
      - hammeritem:genshin_mooncake
      - hammeritem:stardrew_mooncake
      - hammeritem:loutus_yolk_mooncake
      - hammeritem:redbean_mooncake
      - hammeritem:icypurple_mooncake
      - hammeritem:coco_mooncake
      - hammeritem:pork_mooncake
      - hammeritem:tea_mooncake
      - hammeritem:eaten_seasame_mooncake
      - hammeritem:yolk_mooncake
      - hammeritem:cream_coconut_mooncake
      - hammeritem:prismarine_mooncake
      - hammeritem:creeper_mooncake
      - hammeritem:nether_mooncake
